### ISSUE TITLE
Telescope picker doesnt switch buffer

### ISSUE THREAD

**Issue by Fabian-programmer** [tiagovla/scope.nvim#10]
Hey, I really like the new telescope buffer selector. But when I press <CR> it doesn't switch to that buffer.

![2023-06-23_17h27_37](https://github.com/tiagovla/scope.nvim/assets/65787013/01a4881e-c992-4f78-abb7-7f87caccf267)

**Comment by tiagovla** [comment]
Whoops, it should be fixed now.

**Comment by Fabian-programmer** [comment]
Works as expected now. Thanks :)
