### ISSUE TITLE
Scope.nvim cache not updated when exiting Neovim

### ISSUE THREAD

**Issue by EmreDogann** [tiagovla/scope.nvim#11]
There is an issue with the way scope.nvim updates its cache. For example, in the following scenario:
1. Open neovim and load/create session.
	1. `ScopeSaveState` is called in the session manager's pre-save hook.
	2. `ScopeLoadState` is called in the session manager's post-load hook.
3. Execute `:tabnew` to create a new tab.
4. Open files in that newly created tab.
5. Then, after opening that file, immediately run `:qa` or `:wqa` (i.e. don't switch tabs).
6. Upon reloading the session, the opened files are not recognized by Scope.nvim, leading to the tabline only showing the currently active buffer.

After some testing, when exiting neovim using `:qa` or `:wqa`, the `on_tab_leave()` function does not get called. From my understanding, this is because `TabLeave` is not triggered when directly exiting vim. This means that if you create a new tab and open files in that new tab, Scope.nvim will not update its cache to include the new files in that tab _**unless**_ you switch to a different tab, in which case, the `TabLeave` event is triggered, therefore calling `on_tab_leave()`.

As a quick fix, I modified `init.lua` to the following:
```lua
function M._setup()
    local group = vim.api.nvim_create_augroup("ScopeAU", {})
    vim.api.nvim_create_autocmd("TabEnter", { group = group, callback = core.on_tab_enter })
    vim.api.nvim_create_autocmd({ "TabLeave", "VimLeavePre" }, { group = group, callback = core.on_tab_leave })		<--- Fix: Added "VimLeavePre" event.
    vim.api.nvim_create_autocmd("TabClosed", { group = group, callback = core.on_tab_closed })
    vim.api.nvim_create_autocmd("TabNewEntered", { group = group, callback = core.on_tab_new_entered })
    vim.api.nvim_create_user_command("ScopeSaveState", session.save_state, {})
    vim.api.nvim_create_user_command("ScopeLoadState", session.load_state, {})
    vim.api.nvim_create_user_command("ScopeList", core.print_summary, {}) --TODO: improve this
    if config.restore_state then
        -- vim.api.nvim_create_autocmd("SessionLoadPost", { group = group, callback = session.load_state }) --TODO: implement event behavior
    end
end
```

Now, when exiting vim, the `on_tab_leave()` function is called in the `VimLeavePre` event, therefore updating the cache without having to switch tabs first. My session manager (nvim-possession) calls `:mksession` in the `VimLeave` event so that's why I used VimLeavePre, I'm not sure if this would work for other session managers.

It seems to have fixed the issue. What do you think of this?

**Comment by tiagovla** [comment]
Since we don't know how other session managers do it, maybe something like this?
```lua
vim.api.nvim_create_user_command("ScopeSaveState", function()
    core.on_tab_leave()
    core.on_tab_enter()
    session.save_state()
end, {})
```
Could you test if this works in your case?

**Comment by EmreDogann** [comment]
Sorry for the late response,

Yeah, just tried it out, and that seems to work great. One suggestion, the README mentions these commands however I think a little bit extra about recommended places to call them would clear some things up for new people.

**Comment by tiagovla** [comment]
> Sorry for the late response,
> 
> Yeah, just tried it out, and that seems to work great. One suggestion, the README mentions these commands however I think a little bit extra about recommended places to call them would clear some things up for new people.

I don't use any session manager at the moment. Would you mind including a subsection in the README that demonstrates how to config your session manager plugin? It would be great to have a minimal configuration example. Maybe others would be willing to contribute with other session managers as well.

**Comment by EmreDogann** [comment]
Sure thing!

**Comment by EmreDogann** [comment]
My session manager doesn't have a pre_save_hook so I forked and added one. I will submit a pull request to get one added, after it's approved I'll update the readme.
