### ISSUE TITLE
Not working in LazyVim

### ISSUE THREAD

**Issue by juridiener** [tiagovla/scope.nvim#27]
Hello this plugin is amazing but unfortunately it does not work in LazyVim. I installed it under the plugin directory like the docs are showing this in LazyVim. And then i open two files and open the third file in a tab and i can see all buffers. 

Do i need some configurations? 

Any help is very appreciate. I hope i get this working, this would be help me a lot to be more productive.

**Comment by juridiener** [comment]
Sorry my fault, i forgot to call the setup.

**Comment by Sairyss** [comment]
Same happened to me, spent like 20 minutes trying to make it work. This should be in the readme:

```lua
  {
    "tiagovla/scope.nvim",
    config = function()
      require("scope").setup({
        hooks = {
          pre_tab_enter = function()
            -- Your custom logic to run before entering a tab
          end,
        },
      })
    end,
  },
```
