### ISSUE TITLE
If I use fzf-lua instead of telescope, I get an error

### ISSUE THREAD

**Issue by gengdz** [tiagovla/scope.nvim#29]
Does this plugin support fzf-lua?

**Comment by tiagovla** [comment]
What's the error? It shouldn't be related.

**Comment by gengdz** [comment]
@tiagovla 
![image](https://github.com/tiagovla/scope.nvim/assets/41912568/6cb7096b-a2d0-43fd-a6ae-e1f28dd2f1cc)

**Comment by tiagovla** [comment]
Could you share how you are loading scope.nvim and if you are passing any options?

**Comment by gengdz** [comment]
```lua
  {
    "tiagovla/scope.nvim",
    enabled = true,
    lazy = true,
    event = "VeryLazy",
    config = function()
      vim.opt.sessionoptions = { -- required
        "buffers",
        "tabpages",
        "globals",
      }
      require("telescope").load_extension("scope")
      -- init.lua
      require("scope").setup({})
    end,
  },

```
Do you think I should remove this line require("telescope").load_extension("scope")?

**Comment by gengdz** [comment]
It's working now. I'm going to close this issue.
