### ISSUE TITLE
Tab Rename Feature

### ISSUE THREAD

**Issue by jeeeem** [tiagovla/scope.nvim#3]
Firstly, thanks for making this plugin as this is the workflow I am looking for a lua plugin. 

From what I understand in the GIF workflow, does this plugin work like [vim-ctrlspace](https://github.com/vim-ctrlspace/vim-ctrlspace) in such a way that you can group buffers in different tabs and you can navigate those buffers only in those tab groups. Is it possible to have a feature to rename the tab groups?

**Comment by tiagovla** [comment]
That's exactly it. This plugin itself just manages which buffers are hidden/shown in every tab. Renaming tabs should be implemented in the bufferline plugin (e.g. [bufferline.nvim](https://github.com/akinsho/bufferline.nvim)).

**Comment by tiagovla** [comment]
Intead of a bufferline plugin + scope.nvim, maybe give this a look https://github.com/kdheepak/tabline.nvim.

**Comment by minego** [comment]
If you are using https://github.com/nvim-lualine/lualine.nvim to control the look of your tabline you can use `:LualineRenameTab` to rename a tab.
