### ISSUE TITLE
Feature: cached tab number relative buffer count

### ISSUE THREAD

**Issue by qaptoR** [tiagovla/scope.nvim#33]
It would be great for use with plugins like tabby.nvim to be able to indicate on the tabs how many buffers are scoped to the tab.

I tried relocating the code used to get the buffer list from the telescope extension into a utility module, but the whole just got too frustrating, and that's when I noticed there is already a cache in the core. So what if we could index into that cache by tab number to get the count.

Maybe this is already possible, and I'm just missing how easy it should be.

**Comment by tiagovla** [comment]
You can check how many buffers there are with:
```lua
n_buffers = #require("scope.core").cache[tab_id]
```

**Comment by qaptoR** [comment]
Wow, thank you! I really appreciate that you were forward thinking to include it!
I suppose in the future I should just try to test something like that when I discover a 'cache' exists, on the off chance the developer and I think alike.

Cheer!
