### ISSUE TITLE
When I create a tab and change to another directory from this tab, my original working folder on my first tab is changed to the last directory open

### ISSUE THREAD

**Issue by jrafaaael** [tiagovla/scope.nvim#6]
If I'm in `projects/python/my_project_1` and run the command `:tabnew` I create a second tab in `projects/python/my_project_1` . If in this second tab I want to open another project i.e `projects/python/my_project_2` I run the command `:cd ../my_project_2` and works perfectly. The problem is that in my first tab with the location `projects/python/my_project_1` is also changed to `projects/python/my_project_2`

**Comment by tiagovla** [comment]
@jrafaaael `:cd` is global as far as I know. Have you tried `:lcd` and `:tcd`? I also have this personal plugin to handle this exact situation https://github.com/tiagovla/buffercd.nvim.
